name: "Nightly Firmware CI/CD for MIDI_Host"

on:
  workflow_dispatch:
  push:
    paths:
      - 'firmware/CMakeLists.txt'
      - '.github/workflows/MIDI_Host_Firmware.yml'
      - 'firmware/main/*.c'
      - 'firmware/main/*.h'
      - 'firmware/main/CMakeLists.txt'
      - 'firmware/main/Kconfig.projbuild'
  pull_request:
    paths:
      - 'firmware/CMakeLists.txt'
      - '.github/workflows/MIDI_Host_Firmware.yml'
      - 'firmware/main/*.c'
      - 'firmware/main/*.h'
      - 'firmware/main/CMakeLists.txt'
      - 'firmware/main/Kconfig.projbuild'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: esp32s3
        path: 'firmware'

    - name: Run Unit Tests
      run: |
        cd firmware/main/host_test
        ./test.sh
        ./test.sh >> test.txt

    - uses: tsickert/discord-webhook@v4.0.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        content: "Heyo, Knot Unit Tests are ready!"
        filename: "firmware/main/host_test/test.txt"

    - name: Convert to uf2
      run: |
        cd firmware
        sudo python3 ./tools/uf2conv.py -f ESP32S3 ./build/midi_host_fw.bin -b 0x0 -c -o ./output/midi_host_fw.uf2


    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Nightly Knot Firmware
        path: firmware/output/
        if-no-files-found: warn