name: "Firmware CI/CD for MIDI_Host"

on:
  workflow_dispatch:
  push:
    paths:
      - 'firmware/CMakeLists.txt'
      - '.github/workflows/MIDI_Host_Firmware.yml'
      - 'firmware/main/*.c'
      - 'firmware/main/*.h'
      - 'firmware/main/CMakeLists.txt'
      - 'firmware/main/Kconfig.projbuild'
  pull_request:
    paths:
      - 'firmware/CMakeLists.txt'
      - '.github/workflows/MIDI_Host_Firmware.yml'
      - 'firmware/main/*.c'
      - 'firmware/main/*.h'
      - 'firmware/main/CMakeLists.txt'
      - 'firmware/main/Kconfig.projbuild'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: esp32s3
        path: 'firmware'
	command: esptool.py merge_bin -o ../your_final_output.bin @flash_args

    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: FabPCB_Output
        path: firmware/build/
        if-no-files-found: warn